script: |
  sudo git config --global --add safe.directory /var/www/site
  cd /var/www/site
  sudo git pull
  sudo cp index.html /var/www/html/index.nginx-debian.html
  sudo systemctl reload nginx
            git config --global --add safe.directory /var/www/site
            cd /var/www/site
            git pull
            cp index.html /var/www/html/index.nginx-debian.html
            systemctl reload nginx
